---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if Stream Producer is already installed.
  stat: path="{{ stream_producer_path }}/{{ stream_producer_file }}"
  register: stream_producer_installed

- name: Download stream producer
  get_url:
    url: "https://raw.githubusercontent.com/Senzing/stream-producer/{{ stream_producer_version }}/stream-producer.py"
    dest: "{{ stream_producer_path }}/{{ stream_producer_file }}"
    mode: '0755'
  when: not stream_producer_installed.stat.exists

- name: Download stream producer requirements file
  get_url:
    url: "https://raw.githubusercontent.com/Senzing/stream-producer/{{ stream_producer_version }}/requirements.txt"
    dest: "{{ stream_producer_dependency_file }}"
    mode: '0755'
  when: not stream_producer_installed.stat.exists

- name: Include python 3.8 install tasks
  include_tasks: "install-python38-{{ ansible_os_family }}.yml"

- name: Install Stream Producer's dependencies
  command: pip3.8 install -r {{ stream_producer_dependency_file }}

- name: Make python 3.8 an alternative with high priority
  command: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 10
