- name: Define stream producer path.
  set_fact:
    stream_producer_path: "/usr/local/bin"
  when: stream_producer_path is not defined

- name: Define stream producer file
  set_fact:
    stream_producer_path: "stream-producer.py"
  when: stream_producer_file is not defined

- name: Define stream producer dependencies file
  set_fact:
    stream_producer_dependency_file: "/tmp/requirements.txt"
  when: stream_producer_dependency_file is not defined
