---
- name: Converge
  pre_tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
      register: required_packages_check
  hosts: all
  tasks:
    - name: "Include ansible-role-stream-producer"
      include_role:
        name: "ansible-role-stream-producer"
