---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: python:3.8.5-buster
    pre_build_image: true
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
provisioner:
  name: ansible
verifier:
  name: ansible
