---
- name: Intall environmental components if needed
  yum:
    name:
      - "{{ item }}"
    state: present
  loop:
    - python3-pip
    - gcc
    - make
    - openssl-devel
    - bzip2-devel
    - libffi-devel
    - git
    - dnf
  when: "'{{ item }}' not in required_packages_check.ansible_facts.packages"

- name: Download python3.8 file
  get_url:
    url: https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz
    dest: /tmp/Python-3.8.5.tgz
    mode: '0777'

- name: Extract python3.8
  unarchive:
    src: /tmp/Python-3.8.5.tgz
    dest: /tmp
    remote_src: yes

- name: Install python3.8
  shell: cd /tmp/Python-3.8.5 && sudo ./configure --enable-optimizations && sudo make altinstall
  args:
    executable: /bin/bash

- name: Install python3 packages
  pip:
    name:
      - dnf
    executable: pip3
    state: forcereinstall
  vars:
    ansible_python_interpreter: /usr/bin/python3
